"""Fanuc-style postprocessor — conservative Fanuc-compatible G-code output."""


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to Fanuc-compatible G-code.

    Generates safe, conservative output. Operations that cannot be fully
    interpreted produce commented placeholders rather than unsafe moves.
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "mill")
    safe_z = operation_plan.get("safe_z", 10.0)
    wcs = operation_plan.get("work_coordinate_system", "G54")
    assumptions = operation_plan.get("assumptions", [])
    warnings = operation_plan.get("warnings", [])

    # --- Header ---
    lines.append(f"(GENERATED BY GENAI4G CNC — POSTPROCESSOR: FANUC)")
    lines.append(f"(MACHINE TYPE: {machine_type.upper()})")
    lines.append(f"(UNITS: {units.upper()})")
    lines.append(f"(WORK COORDINATE SYSTEM: {wcs})")
    lines.append(f"(SAFE Z: {safe_z})")
    if assumptions:
        lines.append("(ASSUMPTIONS:)")
        for a in assumptions:
            lines.append(f"(  - {a})")
    if warnings:
        lines.append("(WARNINGS:)")
        for w in warnings:
            lines.append(f"(  ! {w})")
    lines.append("%")
    lines.append("O0001")

    # --- Safety setup ---
    lines.append("G17 G40 G49 G80 (SAFETY CANCEL)")
    unit_code = "G21" if units == "mm" else "G20"
    lines.append(f"{unit_code} (UNITS: {'MM' if units == 'mm' else 'INCH'})")
    lines.append("G90 (ABSOLUTE POSITIONING)")
    lines.append("G94 (FEED PER MINUTE)")
    lines.append(f"{wcs} (WORK COORDINATE SYSTEM)")

    # --- Operations ---
    operations = operation_plan.get("operations", [])
    tools = {t.get("tool_number"): t for t in operation_plan.get("tools", []) if isinstance(t, dict)}

    if not operations:
        lines.append("(NO OPERATIONS DEFINED — SAFE PROGRAM SKELETON ONLY)")
    else:
        current_tool: int | None = None
        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"(SKIPPED NON-DICT OPERATION: {op!r})")
                continue

            op_name = op.get("name", "UNNAMED OPERATION")
            op_type = op.get("type", "unknown")
            tool_num = op.get("tool_number")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            spindle = op.get("spindle_rpm")
            depth = op.get("depth_mm")
            params = op.get("parameters", {})

            lines.append(f"")
            lines.append(f"({op_name.upper()} — TYPE: {op_type.upper()})")

            # Tool change if needed
            if tool_num is not None and tool_num != current_tool:
                tool_info = tools.get(tool_num, {})
                desc = tool_info.get("description", "")
                lines.append(f"(TOOL {tool_num}: {desc})")
                lines.append(f"T{tool_num:02d} M06 (TOOL CHANGE)")
                current_tool = tool_num
            elif tool_num is None:
                lines.append("(WARNING: NO TOOL NUMBER — SKIPPING TOOL CHANGE)")

            # Retract to safe Z before any motion
            lines.append(f"G00 Z{safe_z:.3f} (RETRACT TO SAFE Z)")

            # Spindle start
            if spindle:
                lines.append(f"S{int(spindle)} M03 (SPINDLE CW)")
            else:
                lines.append("(WARNING: NO SPINDLE SPEED DEFINED)")

            # Operation-specific placeholder
            if op_type in ("face_mill", "face"):
                _append_face_mill(lines, op, feedrate, depth, safe_z)
            elif op_type in ("pocket", "pocket_mill"):
                _append_pocket(lines, op, feedrate, depth, safe_z)
            elif op_type in ("profile", "contour"):
                _append_profile(lines, op, feedrate, depth, safe_z)
            elif op_type in ("drill", "drilling"):
                _append_drill(lines, op, feedrate, depth, safe_z)
            else:
                lines.append(f"(TODO: OPERATION TYPE '{op_type}' NOT YET IMPLEMENTED)")
                lines.append(f"(PARAMETERS: {params})")

            # Retract after operation
            lines.append(f"G00 Z{safe_z:.3f} (RETRACT)")
            lines.append("M05 (SPINDLE STOP)")
            lines.append("M09 (COOLANT OFF)")

    # --- Program end ---
    lines.append("")
    lines.append("G28 G91 Z0. (RETURN Z TO HOME)")
    lines.append("G90")
    lines.append("M30 (PROGRAM END)")
    lines.append("%")

    return "\n".join(lines)


def _append_face_mill(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    x_start = params.get("x_start", 0.0)
    y_start = params.get("y_start", 0.0)
    x_end = params.get("x_end", 100.0)
    stepover = op.get("stepover_mm", 10.0)
    z_cut = -abs(depth) if depth else -1.0
    f = feedrate or 500

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f} (RAPID TO START)")
    lines.append(f"G01 Z{z_cut:.3f} F{f:.0f} (PLUNGE)")
    y = y_start
    direction = 1
    while y <= params.get("y_end", 100.0) + stepover:
        x_to = x_end if direction > 0 else x_start
        lines.append(f"G01 X{x_to:.3f} Y{y:.3f} F{f:.0f}")
        y += stepover
        direction *= -1
    lines.append(f"G00 Z{safe_z:.3f}")


def _append_pocket(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    lines.append("(POCKET: SEE PARAMETERS FOR GEOMETRY)")
    lines.append(f"(PARAMETERS: {params})")
    lines.append("(TODO: Full pocket cycle not yet generated — manual programming required)")
    f = feedrate or 400
    z_cut = -abs(depth) if depth else -5.0
    lines.append(f"(PLUNGE DEPTH WOULD BE: Z{z_cut:.3f} F{f:.0f})")


def _append_profile(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    lines.append("(PROFILE: SEE PARAMETERS FOR GEOMETRY)")
    lines.append(f"(PARAMETERS: {params})")
    lines.append("(TODO: Full profile cycle not yet generated — manual programming required)")


def _append_drill(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    holes = params.get("holes", [])
    f = feedrate or 200
    z_cut = -abs(depth) if depth else -10.0

    if holes:
        for h in holes:
            x, y = h.get("x", 0.0), h.get("y", 0.0)
            lines.append(f"G83 X{x:.3f} Y{y:.3f} Z{z_cut:.3f} R2.000 Q2.000 F{f:.0f} (PECK DRILL)")
        lines.append("G80 (CANCEL CANNED CYCLE)")
    else:
        lines.append(f"(DRILL: NO HOLE COORDINATES PROVIDED)")
        lines.append(f"(WOULD DRILL TO Z{z_cut:.3f} F{f:.0f})")
