"""Fanuc-style postprocessor — conservative Fanuc-compatible G-code output.

Generated programs are deliberately conservative:
- Operations with missing required parameters are skipped with a comment.
- No unsafe G1 plunge moves without a feedrate.
- No spindle start without a spindle speed.
- Review all output before running on a real machine.
"""


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to Fanuc-compatible G-code.

    Generates safe, conservative output. Operations that cannot be fully
    interpreted produce commented placeholders rather than unsafe moves.
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "mill")
    safe_z = operation_plan.get("safe_z")
    wcs = operation_plan.get("work_coordinate_system", "G54")
    assumptions = operation_plan.get("assumptions", [])
    warnings_plan = operation_plan.get("warnings", [])

    # Determine safe_z for use in motion — if missing, movements that need it are skipped
    _safe_z: float | None = float(safe_z) if safe_z is not None else None

    # --- Header (% first, per Fanuc standard) ---
    lines.append("%")
    lines.append("O0001")
    lines.append("(GENERATED BY GENAI4G CNC — POSTPROCESSOR: FANUC)")
    lines.append("(CONSERVATIVE OUTPUT — REVIEW BEFORE RUNNING ON A MACHINE)")
    lines.append(f"(MACHINE TYPE: {machine_type.upper()})")
    lines.append(f"(UNITS: {units.upper()})")
    lines.append(f"(WORK COORDINATE SYSTEM: {wcs})")
    if _safe_z is not None:
        lines.append(f"(SAFE Z: {_safe_z})")
    else:
        lines.append("(SAFE Z: NOT SPECIFIED)")
    if assumptions:
        lines.append("(ASSUMPTIONS:)")
        for a in assumptions:
            lines.append(f"(  - {a})")
    if warnings_plan:
        lines.append("(PLAN WARNINGS:)")
        for w in warnings_plan:
            lines.append(f"(  ! {w})")

    # --- Safety setup ---
    lines.append("G17 G40 G49 G80 (SAFETY CANCEL: PLANE/COMP/TLO/CYCLE)")
    unit_code = "G21" if units == "mm" else "G20"
    lines.append(f"{unit_code} (UNITS: {'MM' if units == 'mm' else 'INCH'})")
    lines.append("G90 (ABSOLUTE POSITIONING)")
    lines.append("G94 (FEED PER MINUTE)")
    lines.append(f"{wcs} (WORK COORDINATE SYSTEM)")

    # Initial safe retract (only if safe_z is known)
    if _safe_z is not None:
        lines.append(f"G00 Z{_safe_z:.3f} (INITIAL RETRACT TO SAFE Z)")

    # --- Operations ---
    operations = operation_plan.get("operations", [])
    # Build tool lookup by both tool_number and id
    tools: dict = {}
    for t in operation_plan.get("tools", []):
        if not isinstance(t, dict):
            continue
        if t.get("tool_number") is not None:
            tools[t["tool_number"]] = t
        if t.get("id") is not None:
            tools[t["id"]] = t

    if not operations:
        lines.append("(NO OPERATIONS DEFINED — SAFE PROGRAM SKELETON ONLY)")
    else:
        current_tool: object = None
        # Spindle state tracking — avoids redundant S.../M03 between ops at same speed
        current_spindle_speed: int | None = None
        spindle_active: bool = False

        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"(SKIPPED NON-DICT OPERATION: {op!r})")
                continue

            op_name = op.get("name") or op.get("description") or "UNNAMED OPERATION"
            op_type = op.get("type", "unknown")
            # Support both tool_number (int) and tool_id (str like "T1")
            tool_ref = op.get("tool_number") or op.get("tool_id")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            spindle = op.get("spindle_rpm") or op.get("spindle_speed")
            depth = op.get("depth_mm")
            params = op.get("parameters", {})

            lines.append("")
            lines.append(f"({op_name.upper()} — TYPE: {op_type.upper()})")

            # Tool change if needed
            if tool_ref is not None and tool_ref != current_tool:
                tool_info = tools.get(tool_ref, {})
                desc = tool_info.get("description") or tool_info.get("name") or ""
                lines.append(f"(TOOL {tool_ref}: {desc})")
                try:
                    t_num = int(str(tool_ref).lstrip("Tt"))
                    lines.append(f"T{t_num:02d} M06 (TOOL CHANGE)")
                except ValueError:
                    lines.append(f"(TOOL CHANGE FOR: {tool_ref})")
                current_tool = tool_ref
            elif tool_ref is None:
                lines.append("(WARNING: NO TOOL REFERENCE — SKIPPING TOOL CHANGE)")

            # Retract to safe Z before any motion
            if _safe_z is not None:
                lines.append(f"G00 Z{_safe_z:.3f} (RETRACT TO SAFE Z)")
            else:
                lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT SKIPPED)")

            # Spindle management — start once per speed, avoid redundant M03 restarts
            spindle_int = int(spindle) if spindle else None
            if spindle_int:
                if spindle_active and current_spindle_speed == spindle_int:
                    lines.append(f"(SPINDLE ALREADY RUNNING AT S{spindle_int} — NO RESTART)")
                else:
                    if spindle_active:
                        lines.append("M05 (SPINDLE SPEED CHANGE — STOP BEFORE RESTART)")
                    lines.append(f"S{spindle_int} M03 (SPINDLE CW)")
                    current_spindle_speed = spindle_int
                    spindle_active = True
            else:
                if spindle_active:
                    lines.append("M05 (SPINDLE STOP — NO SPEED FOR THIS OPERATION)")
                    spindle_active = False
                    current_spindle_speed = None
                lines.append("(WARNING: NO SPINDLE SPEED DEFINED — M03 SKIPPED)")

            # Operation-specific G-code
            if op_type in ("face_mill", "face"):
                _append_face_mill(lines, op, feedrate, depth, _safe_z)
            elif op_type in ("pocket", "pocket_mill"):
                _append_pocket(lines, op, feedrate, depth, _safe_z)
            elif op_type in ("profile", "contour"):
                _append_profile(lines, op, feedrate, depth, _safe_z)
            elif op_type in ("drill", "drilling", "peck_drill", "bore", "ream"):
                _append_drill(lines, op, feedrate, depth, _safe_z)
            else:
                lines.append(f"(TODO: OPERATION TYPE '{op_type}' NOT YET IMPLEMENTED)")
                lines.append(f"(PARAMETERS: {params})")

            # Retract after operation — spindle stays running for next op
            if _safe_z is not None:
                lines.append(f"G00 Z{_safe_z:.3f} (RETRACT AFTER OPERATION)")
            lines.append("M09 (COOLANT OFF)")

        # Stop spindle after all operations if still running
        if spindle_active:
            lines.append("M05 (SPINDLE STOP — END OF OPERATIONS)")

    # --- Program end ---
    lines.append("")
    if _safe_z is not None:
        lines.append("G28 G91 Z0. (RETURN Z TO HOME)")
        lines.append("G90")
    lines.append("M30 (PROGRAM END)")
    lines.append("%")

    return "\n".join(lines)


def _append_face_mill(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    params = op.get("parameters", {})
    x_start = params.get("x_start", 0.0)
    y_start = params.get("y_start", 0.0)
    x_end = params.get("x_end", 100.0)
    stepover = op.get("stepover_mm", 10.0)
    z_cut = -abs(depth) if depth else -1.0
    f = feedrate or 500

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f} (RAPID TO START)")
    lines.append(f"G01 Z{z_cut:.3f} F{f:.0f} (PLUNGE)")
    y = y_start
    direction = 1
    while y <= params.get("y_end", 100.0) + stepover:
        x_to = x_end if direction > 0 else x_start
        lines.append(f"G01 X{x_to:.3f} Y{y:.3f} F{f:.0f}")
        y += stepover
        direction *= -1
    if safe_z is not None:
        lines.append(f"G00 Z{safe_z:.3f}")


def _append_pocket(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    params = op.get("parameters", {})
    lines.append("(POCKET: SEE PARAMETERS FOR GEOMETRY)")
    lines.append(f"(PARAMETERS: {params})")
    lines.append("(TODO: Full pocket cycle not yet generated — manual programming required)")
    f = feedrate or 400
    z_cut = -abs(depth) if depth else -5.0
    lines.append(f"(PLUNGE DEPTH WOULD BE: Z{z_cut:.3f} F{f:.0f})")


def _append_profile(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    params = op.get("parameters", {})
    lines.append("(PROFILE: SEE PARAMETERS FOR GEOMETRY)")
    lines.append(f"(PARAMETERS: {params})")
    lines.append("(TODO: Full profile cycle not yet generated — manual programming required)")


def _append_drill(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    """Generate drill moves for a single operation.

    Handles two formats:
    - New (one operation per hole): parameters = {x, y, z}
    - Old (multiple holes):         parameters = {holes: [{x, y}, ...], z via depth}

    Safety rules:
    - No G1 plunge without feedrate.
    - No motion without coordinates.
    - No motion without safe_z (retract skipped with comment).
    """
    params = op.get("parameters", {})
    feedrate_val = feedrate

    # --- New format: single hole with x, y, z in parameters ---
    x = params.get("x")
    y = params.get("y")
    z = params.get("z")

    if x is not None and y is not None and z is not None:
        if feedrate_val is None:
            lines.append(
                f"(SKIPPED DRILL MOVE AT X{x} Y{y} Z{z} — NO FEEDRATE DEFINED)"
            )
            return
        z_float = float(z)
        # Ensure z is negative (below workpiece surface)
        if z_float > 0:
            z_float = -z_float
            lines.append(f"(NOTE: Z target converted to negative: Z{z_float:.3f})")
        lines.append(f"G00 X{float(x):.3f} Y{float(y):.3f} (RAPID TO HOLE POSITION)")
        lines.append(f"G01 Z{z_float:.3f} F{float(feedrate_val):.3f} (DRILL PLUNGE)")
        if safe_z is not None:
            lines.append(f"G00 Z{safe_z:.3f} (RETRACT TO SAFE Z)")
        else:
            lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT AFTER DRILL SKIPPED)")
        return

    # --- Old format: holes list ---
    holes = params.get("holes", [])
    z_cut = -abs(depth) if depth else -10.0
    f_val = feedrate_val or 200

    if holes:
        for h in holes:
            hx = h.get("x", 0.0)
            hy = h.get("y", 0.0)
            lines.append(f"G00 X{float(hx):.3f} Y{float(hy):.3f} (RAPID TO HOLE)")
            lines.append(f"G01 Z{z_cut:.3f} F{float(f_val):.3f} (DRILL PLUNGE)")
            if safe_z is not None:
                lines.append(f"G00 Z{safe_z:.3f} (RETRACT)")
            else:
                lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT SKIPPED)")
    else:
        lines.append("(DRILL: NO HOLE COORDINATES PROVIDED — SKIPPING DRILL MOVE)")
        lines.append(f"(WOULD DRILL TO Z{z_cut:.3f} F{f_val:.3f} IF COORDINATES WERE GIVEN)")
