"""Fanuc-style postprocessor — conservative Fanuc-compatible G-code output.

Generated programs are deliberately conservative:
- Operations with missing required parameters are skipped with a comment.
- No unsafe G1 plunge moves without a feedrate.
- No spindle start without a spindle speed.
- Review all output before running on a real machine.
"""

from __future__ import annotations

from cnc.postprocessors.common import (
    get_safe_z,
    get_units_code,
    get_work_coordinate_system,
)


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to Fanuc-compatible G-code.

    Generates safe, conservative output. Operations that cannot be fully
    interpreted produce commented placeholders rather than unsafe moves.
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "mill")
    _safe_z: float | None = get_safe_z(operation_plan)
    wcs = get_work_coordinate_system(operation_plan)
    assumptions = operation_plan.get("assumptions", [])
    warnings_plan = operation_plan.get("warnings", [])

    # --- Header (% first, per Fanuc standard) ---
    lines.append("%")
    lines.append("O0001")
    lines.append("(GENERATED BY GENAI4G CNC — POSTPROCESSOR: FANUC)")
    lines.append("(CONSERVATIVE OUTPUT — REVIEW BEFORE RUNNING ON A MACHINE)")
    lines.append(f"(MACHINE TYPE: {machine_type.upper()})")
    lines.append(f"(UNITS: {units.upper()})")
    lines.append(f"(WORK COORDINATE SYSTEM: {wcs})")
    if _safe_z is not None:
        lines.append(f"(SAFE Z: {_safe_z})")
    else:
        lines.append("(SAFE Z: NOT SPECIFIED)")
    if assumptions:
        lines.append("(ASSUMPTIONS:)")
        for a in assumptions:
            lines.append(f"(  - {a})")
    if warnings_plan:
        lines.append("(PLAN WARNINGS:)")
        for w in warnings_plan:
            lines.append(f"(  ! {w})")

    # --- Safety setup ---
    lines.append("G17 G40 G49 G80 (SAFETY CANCEL: PLANE/COMP/TLO/CYCLE)")
    unit_code = get_units_code(units)
    lines.append(f"{unit_code} (UNITS: {'MM' if units == 'mm' else 'INCH'})")
    lines.append("G90 (ABSOLUTE POSITIONING)")
    lines.append("G94 (FEED PER MINUTE)")
    lines.append(f"{wcs} (WORK COORDINATE SYSTEM)")

    # Initial safe retract (only if safe_z is known)
    if _safe_z is not None:
        lines.append(f"G00 Z{_safe_z:.3f} (INITIAL RETRACT TO SAFE Z)")

    # --- Operations ---
    operations = operation_plan.get("operations", [])
    # Build tool lookup by both tool_number and id
    tools: dict = {}
    for t in operation_plan.get("tools", []):
        if not isinstance(t, dict):
            continue
        if t.get("tool_number") is not None:
            tools[t["tool_number"]] = t
        if t.get("id") is not None:
            tools[t["id"]] = t

    if not operations:
        lines.append("(NO OPERATIONS DEFINED — SAFE PROGRAM SKELETON ONLY)")
    else:
        current_tool: object = None
        # Spindle state tracking — avoids redundant S.../M03 between ops at same speed
        current_spindle_speed: int | None = None
        spindle_active: bool = False

        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"(SKIPPED NON-DICT OPERATION: {op!r})")
                continue

            op_name = op.get("name") or op.get("description") or "UNNAMED OPERATION"
            op_type = op.get("type", "unknown")
            # Support both tool_number (int) and tool_id (str like "T1")
            tool_ref = op.get("tool_number") or op.get("tool_id")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            spindle = op.get("spindle_rpm") or op.get("spindle_speed")
            depth = op.get("depth_mm")
            params = op.get("parameters", {})

            lines.append("")
            lines.append(f"({op_name.upper()} — TYPE: {op_type.upper()})")

            # Tool change if needed
            if tool_ref is not None and tool_ref != current_tool:
                tool_info = tools.get(tool_ref, {})
                desc = tool_info.get("description") or tool_info.get("name") or ""
                lines.append(f"(TOOL {tool_ref}: {desc})")
                try:
                    t_num = int(str(tool_ref).lstrip("Tt"))
                    lines.append(f"T{t_num:02d} M06 (TOOL CHANGE)")
                except ValueError:
                    lines.append(f"(TOOL CHANGE FOR: {tool_ref})")
                current_tool = tool_ref
            elif tool_ref is None:
                lines.append("(WARNING: NO TOOL REFERENCE — SKIPPING TOOL CHANGE)")

            # Retract to safe Z before any motion
            if _safe_z is not None:
                lines.append(f"G00 Z{_safe_z:.3f} (RETRACT TO SAFE Z)")
            else:
                lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT SKIPPED)")

            # Spindle management — start once per speed, avoid redundant M03 restarts
            spindle_int = int(spindle) if spindle else None
            if spindle_int:
                if spindle_active and current_spindle_speed == spindle_int:
                    lines.append(f"(SPINDLE ALREADY RUNNING AT S{spindle_int} — NO RESTART)")
                else:
                    if spindle_active:
                        lines.append("M05 (SPINDLE SPEED CHANGE — STOP BEFORE RESTART)")
                    lines.append(f"S{spindle_int} M03 (SPINDLE CW)")
                    current_spindle_speed = spindle_int
                    spindle_active = True
            else:
                if spindle_active:
                    lines.append("M05 (SPINDLE STOP — NO SPEED FOR THIS OPERATION)")
                    spindle_active = False
                    current_spindle_speed = None
                lines.append("(WARNING: NO SPINDLE SPEED DEFINED — M03 SKIPPED)")

            # Operation-specific G-code
            if op_type in ("slot",):
                _append_slot(lines, op, feedrate, _safe_z)
            elif op_type in ("facing",):
                _append_facing(lines, op, feedrate, _safe_z)
            elif op_type in ("face_mill", "face"):
                _append_face_mill(lines, op, feedrate, depth, _safe_z)
            elif op_type in ("pocket", "pocket_mill"):
                _append_pocket(lines, op, feedrate, depth, _safe_z)
            elif op_type in ("profile", "contour"):
                _append_profile(lines, op, feedrate, depth, _safe_z)
            elif op_type in ("drill", "drilling", "peck_drill", "bore", "ream"):
                _append_drill(lines, op, feedrate, depth, _safe_z)
            else:
                lines.append(f"(TODO: OPERATION TYPE '{op_type}' NOT YET IMPLEMENTED)")
                lines.append(f"(PARAMETERS: {params})")

            # Retract after operation — spindle stays running for next op
            if _safe_z is not None:
                lines.append(f"G00 Z{_safe_z:.3f} (RETRACT AFTER OPERATION)")
            lines.append("M09 (COOLANT OFF)")

        # Stop spindle after all operations if still running
        if spindle_active:
            lines.append("M05 (SPINDLE STOP — END OF OPERATIONS)")

    # --- Program end ---
    lines.append("")
    if _safe_z is not None:
        lines.append("G28 G91 Z0. (RETURN Z TO HOME)")
        lines.append("G90")
    lines.append("M30 (PROGRAM END)")
    lines.append("%")

    return "\n".join(lines)


def _append_face_mill(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    params = op.get("parameters", {})
    x_start = params.get("x_start", 0.0)
    y_start = params.get("y_start", 0.0)
    x_end = params.get("x_end", 100.0)
    stepover = op.get("stepover_mm", 10.0)
    z_cut = -abs(depth) if depth else -1.0
    f = feedrate or 500

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f} (RAPID TO START)")
    lines.append(f"G01 Z{z_cut:.3f} F{f:.0f} (PLUNGE)")
    y = y_start
    direction = 1
    while y <= params.get("y_end", 100.0) + stepover:
        x_to = x_end if direction > 0 else x_start
        lines.append(f"G01 X{x_to:.3f} Y{y:.3f} F{f:.0f}")
        y += stepover
        direction *= -1
    if safe_z is not None:
        lines.append(f"G00 Z{safe_z:.3f}")


def _append_pocket(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    """Generate conservative Fanuc raster pocket moves for a rectangular pocket.

    Strategy: for each Z level (step_down increments down to target_z),
    mill parallel rows along X from origin_y to origin_y+height, stepping Y
    by step_over. Direction alternates (boustrophedon) between rows.

    Safety rules:
    - No G1 cutting move without feedrate.
    - No motion without safe_z (skip with comment).
    - No cutter compensation (G41/G42).
    - All parameters taken from operation.parameters.
    """
    params = op.get("parameters", {})

    origin_x = params.get("origin_x")
    origin_y = params.get("origin_y")
    width = params.get("width")
    height = params.get("height")
    target_z = params.get("target_z")
    step_down = params.get("step_down")
    step_over = params.get("step_over")
    f = feedrate

    # Safety: abort if any required parameter is missing
    missing = [
        name for name, val in [
            ("origin_x", origin_x), ("origin_y", origin_y),
            ("width", width), ("height", height),
            ("target_z", target_z), ("step_down", step_down),
            ("step_over", step_over),
        ]
        if val is None
    ]
    if missing:
        lines.append(
            f"(POCKET SKIPPED — MISSING PARAMETERS: {', '.join(missing)})"
        )
        return

    if f is None:
        lines.append(
            f"(POCKET SKIPPED — NO FEEDRATE DEFINED. "
            f"WOULD POCKET {float(width):.3f}x{float(height):.3f} TO Z{float(target_z):.3f})"
        )
        return

    if safe_z is None:
        lines.append("(POCKET SKIPPED — SAFE Z NOT DEFINED)")
        return

    ox = float(origin_x)
    oy = float(origin_y)
    w = float(width)
    h = float(height)
    tz = float(target_z)
    sd = float(step_down)
    so = float(step_over)
    f_val = float(f)

    # Ensure target_z is negative
    if tz > 0:
        tz = -tz
        lines.append(f"(NOTE: target_z sign corrected to Z{tz:.3f})")

    # Clamp step_down to total depth if larger (one pass)
    if sd > abs(tz):
        sd = abs(tz)

    lines.append(
        f"(POCKET: {w:.3f}x{h:.3f} FROM X{ox:.3f} Y{oy:.3f}, "
        f"DEPTH Z{tz:.3f}, STEP-DOWN {sd:.3f}, STEP-OVER {so:.3f})"
    )
    lines.append("(Pocket raster clearing; no cutter compensation applied)")

    # Build Z levels
    z_levels: list[float] = []
    z_current = -sd
    while z_current > tz + 1e-9:
        z_levels.append(z_current)
        z_current -= sd
    z_levels.append(tz)

    for z_pass, z_level in enumerate(z_levels, start=1):
        lines.append(f"(Z PASS {z_pass} — DEPTH Z{z_level:.3f})")
        lines.append(f"G00 Z{safe_z:.3f} (RETRACT TO SAFE Z)")
        lines.append(f"G00 X{ox:.3f} Y{oy:.3f} (RAPID TO POCKET ORIGIN)")
        lines.append(f"G01 Z{z_level:.3f} F{f_val:.3f} (PLUNGE TO DEPTH)")

        y = oy
        row = 0
        direction = 1  # 1 = left-to-right, -1 = right-to-left
        while y <= oy + h + 1e-9:
            row += 1
            x_start = ox if direction == 1 else ox + w
            x_end = ox + w if direction == 1 else ox
            dir_label = "L>R" if direction == 1 else "R>L"
            lines.append(f"(ROW {row} — Y{y:.3f} — {dir_label})")
            lines.append(f"G00 X{x_start:.3f} Y{y:.3f} (RAPID TO ROW START)")
            lines.append(f"G01 X{x_end:.3f} F{f_val:.3f} (CUT ROW)")
            y += so
            direction *= -1

        lines.append(f"G00 Z{safe_z:.3f} (RETRACT AFTER Z LEVEL)")


def _append_profile(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    params = op.get("parameters", {})
    lines.append("(PROFILE: SEE PARAMETERS FOR GEOMETRY)")
    lines.append(f"(PARAMETERS: {params})")
    lines.append("(TODO: Full profile cycle not yet generated — manual programming required)")


def _append_drill(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    """Generate drill moves for a single operation.

    Handles two formats:
    - New (one operation per hole): parameters = {x, y, z}
    - Old (multiple holes):         parameters = {holes: [{x, y}, ...], z via depth}

    Safety rules:
    - No G1 plunge without feedrate.
    - No motion without coordinates.
    - No motion without safe_z (retract skipped with comment).
    """
    params = op.get("parameters", {})
    feedrate_val = feedrate

    # --- New format: single hole with x, y, z in parameters ---
    x = params.get("x")
    y = params.get("y")
    z = params.get("z")

    if x is not None and y is not None and z is not None:
        if feedrate_val is None:
            lines.append(
                f"(SKIPPED DRILL MOVE AT X{x} Y{y} Z{z} — NO FEEDRATE DEFINED)"
            )
            return
        z_float = float(z)
        # Ensure z is negative (below workpiece surface)
        if z_float > 0:
            z_float = -z_float
            lines.append(f"(NOTE: Z target converted to negative: Z{z_float:.3f})")
        lines.append(f"G00 X{float(x):.3f} Y{float(y):.3f} (RAPID TO HOLE POSITION)")
        lines.append(f"G01 Z{z_float:.3f} F{float(feedrate_val):.3f} (DRILL PLUNGE)")
        if safe_z is not None:
            lines.append(f"G00 Z{safe_z:.3f} (RETRACT TO SAFE Z)")
        else:
            lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT AFTER DRILL SKIPPED)")
        return

    # --- Old format: holes list ---
    holes = params.get("holes", [])
    z_cut = -abs(depth) if depth else -10.0
    f_val = feedrate_val or 200

    if holes:
        for h in holes:
            hx = h.get("x", 0.0)
            hy = h.get("y", 0.0)
            lines.append(f"G00 X{float(hx):.3f} Y{float(hy):.3f} (RAPID TO HOLE)")
            lines.append(f"G01 Z{z_cut:.3f} F{float(f_val):.3f} (DRILL PLUNGE)")
            if safe_z is not None:
                lines.append(f"G00 Z{safe_z:.3f} (RETRACT)")
            else:
                lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT SKIPPED)")
    else:
        lines.append("(DRILL: NO HOLE COORDINATES PROVIDED — SKIPPING DRILL MOVE)")
        lines.append(f"(WOULD DRILL TO Z{z_cut:.3f} F{f_val:.3f} IF COORDINATES WERE GIVEN)")


def _append_facing(
    lines: list, op: dict, feedrate, safe_z: float | None
) -> None:
    """Generate conservative Fanuc facing moves for a rectangular area.

    Strategy: alternating parallel passes along X, stepping Y by step_over.
    Each pass retracts to safe_z between rows — conservative but safe.

    Safety rules:
    - No G1 cutting move without feedrate.
    - No motion without safe_z (commented out with warning).
    - No cutter compensation (G41/G42) applied.
    - All parameters taken from operation.parameters.
    """
    params = op.get("parameters", {})

    origin_x = params.get("origin_x")
    origin_y = params.get("origin_y")
    width = params.get("width")
    height = params.get("height")
    target_z = params.get("target_z")
    step_over = params.get("step_over")
    f = feedrate

    # Safety: abort if any required parameter is missing
    missing = [
        name for name, val in [
            ("origin_x", origin_x), ("origin_y", origin_y),
            ("width", width), ("height", height),
            ("target_z", target_z), ("step_over", step_over),
        ]
        if val is None
    ]
    if missing:
        lines.append(
            f"(FACING SKIPPED — MISSING PARAMETERS: {', '.join(missing)})"
        )
        return

    if f is None:
        lines.append(
            f"(FACING SKIPPED — NO FEEDRATE DEFINED. "
            f"WOULD FACE {float(width):.3f}x{float(height):.3f} TO Z{float(target_z):.3f})"
        )
        return

    if safe_z is None:
        lines.append("(FACING SKIPPED — SAFE Z NOT DEFINED)")
        return

    ox = float(origin_x)
    oy = float(origin_y)
    w = float(width)
    h = float(height)
    tz = float(target_z)
    so = float(step_over)
    f_val = float(f)

    # Ensure target_z is negative
    if tz > 0:
        tz = -tz
        lines.append(f"(NOTE: target_z sign corrected to Z{tz:.3f})")

    lines.append(
        f"(FACING: {w:.3f}x{h:.3f} AREA FROM X{ox:.3f} Y{oy:.3f}, "
        f"DEPTH Z{tz:.3f}, STEP-OVER {so:.3f})"
    )
    lines.append("(NOTE: NO CUTTER COMPENSATION — REVIEW PATHS BEFORE USE)")

    y = oy
    direction = 1  # 1 = left-to-right, -1 = right-to-left
    pass_num = 0

    while y <= oy + h + 1e-9:  # 1e-9 tolerance for float rounding
        pass_num += 1
        x_start = ox if direction == 1 else ox + w
        x_end = ox + w if direction == 1 else ox
        dir_label = "L>R" if direction == 1 else "R>L"

        lines.append(f"(PASS {pass_num} — Y{y:.3f} — {dir_label})")
        lines.append(f"G00 Z{safe_z:.3f} (RETRACT TO SAFE Z)")
        lines.append(f"G00 X{x_start:.3f} Y{y:.3f} (RAPID TO PASS START)")
        lines.append(f"G01 Z{tz:.3f} F{f_val:.3f} (PLUNGE TO CUTTING DEPTH)")
        lines.append(f"G01 X{x_end:.3f} F{f_val:.3f} (CUT PASS)")
        lines.append(f"G00 Z{safe_z:.3f} (RETRACT AFTER PASS)")

        y += so
        direction *= -1


def _append_slot(
    lines: list, op: dict, feedrate, safe_z: float | None
) -> None:
    """Generate conservative Fanuc slot moves for a straight groove.

    Strategy: multiple Z passes (step_down per pass) from 0 to target_z.
    Each pass: rapid to start XY at safe_z, plunge to current depth, cut to end, retract.

    Safety rules:
    - No G1 cutting move without feedrate.
    - No motion without safe_z (skip with comment).
    - No cutter compensation (G41/G42).
    - Slot width equals tool diameter — no separate width passes.
    - All parameters taken from operation.parameters.
    """
    params = op.get("parameters", {})

    start_x = params.get("start_x")
    start_y = params.get("start_y")
    length = params.get("length")
    target_z = params.get("target_z")
    direction = params.get("direction")
    step_down = params.get("step_down")
    f = feedrate

    # Safety: abort if any required parameter is missing
    missing = [
        name for name, val in [
            ("start_x", start_x), ("start_y", start_y),
            ("length", length), ("target_z", target_z),
            ("direction", direction), ("step_down", step_down),
        ]
        if val is None
    ]
    if missing:
        lines.append(
            f"(SLOT SKIPPED — MISSING PARAMETERS: {', '.join(missing)})"
        )
        return

    if f is None:
        lines.append(
            f"(SLOT SKIPPED — NO FEEDRATE DEFINED. "
            f"WOULD MILL SLOT LENGTH {float(length):.3f} TO Z{float(target_z):.3f})"
        )
        return

    if safe_z is None:
        lines.append("(SLOT SKIPPED — SAFE Z NOT DEFINED)")
        return

    sx = float(start_x)
    sy = float(start_y)
    ll = float(length)
    tz = float(target_z)
    sd = float(step_down)
    f_val = float(f)
    dir_clean = str(direction).strip().lower()

    # Ensure target_z is negative
    if tz > 0:
        tz = -tz
        lines.append(f"(NOTE: target_z sign corrected to Z{tz:.3f})")

    # Clamp step_down to total depth if larger (one pass)
    if sd > abs(tz):
        sd = abs(tz)

    # Compute end position
    if dir_clean == "x":
        end_x = sx + ll
        end_y = sy
    else:  # "y"
        end_x = sx
        end_y = sy + ll

    lines.append(
        f"(SLOT: LENGTH={ll:.3f} ALONG {dir_clean.upper()}-AXIS "
        f"FROM X{sx:.3f} Y{sy:.3f}, DEPTH Z{tz:.3f}, STEP-DOWN {sd:.3f})"
    )
    lines.append(
        "(Slot width assumed equal to tool diameter; no cutter compensation applied)"
    )

    # Build Z levels for each pass
    z_levels: list[float] = []
    z_current = -sd
    while z_current > tz + 1e-9:
        z_levels.append(z_current)
        z_current -= sd
    z_levels.append(tz)  # always end at target depth

    for pass_num, z_level in enumerate(z_levels, start=1):
        lines.append(f"(PASS {pass_num} — Z{z_level:.3f})")
        lines.append(f"G00 Z{safe_z:.3f} (RETRACT TO SAFE Z)")
        lines.append(f"G00 X{sx:.3f} Y{sy:.3f} (RAPID TO SLOT START)")
        lines.append(f"G01 Z{z_level:.3f} F{f_val:.3f} (PLUNGE TO DEPTH)")
        if dir_clean == "x":
            lines.append(f"G01 X{end_x:.3f} F{f_val:.3f} (CUT ALONG X)")
        else:
            lines.append(f"G01 Y{end_y:.3f} F{f_val:.3f} (CUT ALONG Y)")
        lines.append(f"G00 Z{safe_z:.3f} (RETRACT AFTER PASS)")
