"""GRBL postprocessor — conservative GRBL-compatible G-code output.

GRBL v0 conventions:
- No % tape delimiters
- Comments with ( ... ) style
- G21/G20, G90, G54
- G0/G1, M3/M5
- End sequence: M5, G0 Zsafe, M2
- No tool changer commands (M06)
- No Fanuc-specific canned cycles
- No cutter compensation (G41/G42)
- safe_z missing → operations skipped with comment

Supported operations: drill, facing, slot, pocket, face_mill, laser.
"""

from __future__ import annotations

from cnc.postprocessors.common import (
    fmt,
    get_safe_z,
    get_units_code,
    get_work_coordinate_system,
    iter_operations,
)


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to conservative GRBL-compatible G-code.

    Operations with missing required parameters are skipped with a comment.
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "mill")
    _safe_z: float | None = get_safe_z(operation_plan)
    wcs = get_work_coordinate_system(operation_plan)
    assumptions = operation_plan.get("assumptions", [])
    warnings_plan = operation_plan.get("warnings", [])

    # --- Header (no % for GRBL) ---
    lines.append("(GENERATED BY GENAI4G-CODE — POSTPROCESSOR: GRBL)")
    lines.append("(CONSERVATIVE GRBL-STYLE OUTPUT)")
    lines.append("(REVIEW BEFORE RUNNING ON A MACHINE)")
    lines.append(f"(MACHINE TYPE: {machine_type.upper()})")
    lines.append(f"(UNITS: {units.upper()})")
    lines.append(f"(SAFE Z: {fmt(_safe_z) if _safe_z is not None else 'NOT SPECIFIED'})")
    lines.append(f"(WCS: {wcs})")
    for a in assumptions:
        lines.append(f"(ASSUMPTION: {a})")
    for w in warnings_plan:
        lines.append(f"(WARNING: {w})")

    # --- Safety setup ---
    unit_code = get_units_code(units)
    lines.append(f"{unit_code}")
    lines.append("G90")
    lines.append("G94")
    lines.append(f"{wcs}")

    if _safe_z is not None:
        lines.append(f"G0 Z{fmt(_safe_z)} (INITIAL RETRACT)")

    # --- Operations ---
    operations = iter_operations(operation_plan)
    if not operations:
        lines.append("(NO OPERATIONS DEFINED — SAFE SKELETON ONLY)")
    else:
        spindle_active = False
        current_spindle_speed: int | None = None

        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"(SKIPPED NON-DICT OPERATION: {op!r})")
                continue

            op_name = op.get("name") or op.get("description") or "UNNAMED"
            op_type = op.get("type", "unknown")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            spindle = op.get("spindle_rpm") or op.get("spindle_speed")
            params = op.get("parameters", {})

            lines.append("")
            lines.append(f"({op_name.upper()} — {op_type.upper()})")

            # Retract to safe Z before op
            if _safe_z is not None:
                lines.append(f"G0 Z{fmt(_safe_z)} (RETRACT TO SAFE Z)")
            else:
                lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT SKIPPED)")

            # Spindle management
            spindle_int = int(spindle) if spindle else None
            if spindle_int:
                if spindle_active and current_spindle_speed == spindle_int:
                    lines.append(f"(SPINDLE ALREADY RUNNING AT S{spindle_int})")
                else:
                    if spindle_active:
                        lines.append("M5 (SPINDLE STOP BEFORE SPEED CHANGE)")
                    lines.append(f"S{spindle_int} M3 (SPINDLE ON CW)")
                    current_spindle_speed = spindle_int
                    spindle_active = True
            else:
                lines.append("(WARNING: NO SPINDLE SPEED — M3 SKIPPED)")

            # Operation body
            if op_type in ("drill", "drilling", "peck_drill", "bore", "ream"):
                _append_drill(lines, op, feedrate, _safe_z)
            elif op_type in ("facing",):
                _append_facing(lines, op, feedrate, _safe_z)
            elif op_type in ("slot",):
                _append_slot(lines, op, feedrate, _safe_z)
            elif op_type in ("pocket", "pocket_mill"):
                _append_pocket(lines, op, feedrate, _safe_z)
            elif op_type in ("face_mill", "face"):
                _append_face_mill(lines, op, feedrate, op.get("depth_mm"), _safe_z)
            elif op_type in ("laser_cut", "laser_engrave", "laser_mark"):
                _append_laser(lines, op, feedrate, params)
            else:
                lines.append(f"(TODO: OPERATION TYPE '{op_type}' NOT YET IMPLEMENTED)")
                lines.append(f"(PARAMETERS: {params})")

            # Post-op retract
            if _safe_z is not None:
                lines.append(f"G0 Z{fmt(_safe_z)} (RETRACT AFTER OPERATION)")

        # Stop spindle after all operations
        if spindle_active:
            lines.append("M5 (SPINDLE STOP — END OF OPERATIONS)")

    # --- Program end (GRBL style: M5, G0 Zsafe, M2) ---
    lines.append("")
    lines.append("M5 (SPINDLE OFF)")
    if _safe_z is not None:
        lines.append(f"G0 Z{fmt(_safe_z)} (RETRACT TO SAFE Z)")
    lines.append("M2 (PROGRAM END)")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Operation helpers
# ---------------------------------------------------------------------------


def _append_drill(
    lines: list, op: dict, feedrate, safe_z: float | None
) -> None:
    """Generate GRBL drill moves. Handles single-hole and multi-hole formats."""
    params = op.get("parameters", {})
    f = feedrate

    # New format: single hole with x, y, z in parameters
    x = params.get("x")
    y = params.get("y")
    z = params.get("z")

    if x is not None and y is not None and z is not None:
        if f is None:
            lines.append(f"(SKIPPED DRILL AT X{x} Y{y} Z{z} — NO FEEDRATE)")
            return
        z_float = float(z) if float(z) < 0 else -abs(float(z))
        lines.append(f"G0 X{fmt(float(x))} Y{fmt(float(y))} (RAPID TO HOLE)")
        lines.append(f"G1 Z{fmt(z_float)} F{fmt(float(f))}")
        if safe_z is not None:
            lines.append(f"G0 Z{fmt(safe_z)} (RETRACT)")
        else:
            lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT AFTER DRILL SKIPPED)")
        return

    # Old format: holes list
    holes = params.get("holes", [])
    depth = op.get("depth_mm")
    f_val = f or 200
    z_cut = -abs(float(depth)) if depth else -10.0

    if holes:
        for h in holes:
            hx = float(h.get("x", 0.0))
            hy = float(h.get("y", 0.0))
            lines.append(f"G0 X{fmt(hx)} Y{fmt(hy)} (RAPID TO HOLE)")
            lines.append(f"G1 Z{fmt(z_cut)} F{fmt(float(f_val))}")
            if safe_z is not None:
                lines.append(f"G0 Z{fmt(safe_z)} (RETRACT)")
            else:
                lines.append("(WARNING: SAFE Z NOT DEFINED — RETRACT SKIPPED)")
    else:
        lines.append("(DRILL: NO HOLE COORDINATES PROVIDED — SKIPPING)")
        lines.append(f"(WOULD DRILL TO Z{fmt(z_cut)} F{float(f_val):.0f})")


def _append_facing(
    lines: list, op: dict, feedrate, safe_z: float | None
) -> None:
    """Generate conservative GRBL facing moves for a rectangular area.

    Strategy: alternating parallel passes along X, stepping Y by step_over.
    """
    params = op.get("parameters", {})

    origin_x = params.get("origin_x")
    origin_y = params.get("origin_y")
    width = params.get("width")
    height = params.get("height")
    target_z = params.get("target_z")
    step_over = params.get("step_over")
    f = feedrate

    missing = [
        name for name, val in [
            ("origin_x", origin_x), ("origin_y", origin_y),
            ("width", width), ("height", height),
            ("target_z", target_z), ("step_over", step_over),
        ]
        if val is None
    ]
    if missing:
        lines.append(f"(FACING SKIPPED — MISSING PARAMETERS: {', '.join(missing)})")
        return
    if f is None:
        lines.append(
            f"(FACING SKIPPED — NO FEEDRATE DEFINED. "
            f"WOULD FACE {float(width):.3f}x{float(height):.3f} TO Z{float(target_z):.3f})"
        )
        return
    if safe_z is None:
        lines.append("(FACING SKIPPED — SAFE Z NOT DEFINED)")
        return

    ox = float(origin_x)
    oy = float(origin_y)
    w = float(width)
    h = float(height)
    tz = float(target_z)
    so = float(step_over)
    f_val = float(f)

    if tz > 0:
        tz = -tz
        lines.append(f"(NOTE: target_z sign corrected to Z{fmt(tz)})")

    lines.append(
        f"(FACING: {fmt(w)}x{fmt(h)} FROM X{fmt(ox)} Y{fmt(oy)}, "
        f"DEPTH Z{fmt(tz)}, STEP-OVER {fmt(so)})"
    )
    lines.append("(NO CUTTER COMPENSATION — REVIEW PATHS BEFORE USE)")

    y = oy
    direction = 1
    pass_num = 0
    while y <= oy + h + 1e-9:
        pass_num += 1
        x_start = ox if direction == 1 else ox + w
        x_end = ox + w if direction == 1 else ox
        dir_label = "L>R" if direction == 1 else "R>L"
        lines.append(f"(PASS {pass_num} — Y{fmt(y)} — {dir_label})")
        lines.append(f"G0 Z{fmt(safe_z)} (RETRACT)")
        lines.append(f"G0 X{fmt(x_start)} Y{fmt(y)} (RAPID TO PASS START)")
        lines.append(f"G1 Z{fmt(tz)} F{f_val:.3f} (PLUNGE)")
        lines.append(f"G1 X{fmt(x_end)} F{f_val:.3f} (CUT PASS)")
        lines.append(f"G0 Z{fmt(safe_z)} (RETRACT AFTER PASS)")
        y += so
        direction *= -1


def _append_slot(
    lines: list, op: dict, feedrate, safe_z: float | None
) -> None:
    """Generate conservative GRBL slot moves for a straight groove."""
    params = op.get("parameters", {})

    start_x = params.get("start_x")
    start_y = params.get("start_y")
    length = params.get("length")
    target_z = params.get("target_z")
    direction = params.get("direction")
    step_down = params.get("step_down")
    f = feedrate

    missing = [
        name for name, val in [
            ("start_x", start_x), ("start_y", start_y),
            ("length", length), ("target_z", target_z),
            ("direction", direction), ("step_down", step_down),
        ]
        if val is None
    ]
    if missing:
        lines.append(f"(SLOT SKIPPED — MISSING PARAMETERS: {', '.join(missing)})")
        return
    if f is None:
        lines.append(
            f"(SLOT SKIPPED — NO FEEDRATE DEFINED. "
            f"WOULD MILL SLOT LENGTH {float(length):.3f} TO Z{float(target_z):.3f})"
        )
        return
    if safe_z is None:
        lines.append("(SLOT SKIPPED — SAFE Z NOT DEFINED)")
        return

    sx = float(start_x)
    sy = float(start_y)
    ll = float(length)
    tz = float(target_z)
    sd = float(step_down)
    f_val = float(f)
    dir_clean = str(direction).strip().lower()

    if tz > 0:
        tz = -tz
        lines.append(f"(NOTE: target_z sign corrected to Z{fmt(tz)})")
    if sd > abs(tz):
        sd = abs(tz)

    if dir_clean == "x":
        end_x, end_y = sx + ll, sy
    else:
        end_x, end_y = sx, sy + ll

    lines.append(
        f"(SLOT: LENGTH={fmt(ll)} ALONG {dir_clean.upper()}-AXIS "
        f"FROM X{fmt(sx)} Y{fmt(sy)}, DEPTH Z{fmt(tz)}, STEP-DOWN {fmt(sd)})"
    )
    lines.append("(SLOT WIDTH = TOOL DIAMETER; NO CUTTER COMPENSATION)")

    z_levels: list[float] = []
    z_current = -sd
    while z_current > tz + 1e-9:
        z_levels.append(z_current)
        z_current -= sd
    z_levels.append(tz)

    for pass_num, z_level in enumerate(z_levels, start=1):
        lines.append(f"(PASS {pass_num} — Z{fmt(z_level)})")
        lines.append(f"G0 Z{fmt(safe_z)} (RETRACT)")
        lines.append(f"G0 X{fmt(sx)} Y{fmt(sy)} (RAPID TO SLOT START)")
        lines.append(f"G1 Z{fmt(z_level)} F{f_val:.3f} (PLUNGE)")
        if dir_clean == "x":
            lines.append(f"G1 X{fmt(end_x)} F{f_val:.3f} (CUT ALONG X)")
        else:
            lines.append(f"G1 Y{fmt(end_y)} F{f_val:.3f} (CUT ALONG Y)")
        lines.append(f"G0 Z{fmt(safe_z)} (RETRACT AFTER PASS)")


def _append_pocket(
    lines: list, op: dict, feedrate, safe_z: float | None
) -> None:
    """Generate conservative GRBL raster pocket moves for a rectangular pocket."""
    params = op.get("parameters", {})

    origin_x = params.get("origin_x")
    origin_y = params.get("origin_y")
    width = params.get("width")
    height = params.get("height")
    target_z = params.get("target_z")
    step_down = params.get("step_down")
    step_over = params.get("step_over")
    f = feedrate

    missing = [
        name for name, val in [
            ("origin_x", origin_x), ("origin_y", origin_y),
            ("width", width), ("height", height),
            ("target_z", target_z), ("step_down", step_down),
            ("step_over", step_over),
        ]
        if val is None
    ]
    if missing:
        lines.append(f"(POCKET SKIPPED — MISSING PARAMETERS: {', '.join(missing)})")
        return
    if f is None:
        lines.append(
            f"(POCKET SKIPPED — NO FEEDRATE DEFINED. "
            f"WOULD POCKET {float(width):.3f}x{float(height):.3f} TO Z{float(target_z):.3f})"
        )
        return
    if safe_z is None:
        lines.append("(POCKET SKIPPED — SAFE Z NOT DEFINED)")
        return

    ox = float(origin_x)
    oy = float(origin_y)
    w = float(width)
    h = float(height)
    tz = float(target_z)
    sd = float(step_down)
    so = float(step_over)
    f_val = float(f)

    if tz > 0:
        tz = -tz
        lines.append(f"(NOTE: target_z sign corrected to Z{fmt(tz)})")
    if sd > abs(tz):
        sd = abs(tz)

    lines.append(
        f"(POCKET: {fmt(w)}x{fmt(h)} FROM X{fmt(ox)} Y{fmt(oy)}, "
        f"DEPTH Z{fmt(tz)}, STEP-DOWN {fmt(sd)}, STEP-OVER {fmt(so)})"
    )
    lines.append("(RASTER CLEARING; NO CUTTER COMPENSATION)")

    z_levels: list[float] = []
    z_current = -sd
    while z_current > tz + 1e-9:
        z_levels.append(z_current)
        z_current -= sd
    z_levels.append(tz)

    for z_pass, z_level in enumerate(z_levels, start=1):
        lines.append(f"(Z PASS {z_pass} — DEPTH Z{fmt(z_level)})")
        lines.append(f"G0 Z{fmt(safe_z)} (RETRACT)")
        lines.append(f"G0 X{fmt(ox)} Y{fmt(oy)} (RAPID TO POCKET ORIGIN)")
        lines.append(f"G1 Z{fmt(z_level)} F{f_val:.3f} (PLUNGE)")

        y = oy
        row = 0
        direction = 1
        while y <= oy + h + 1e-9:
            row += 1
            x_start = ox if direction == 1 else ox + w
            x_end = ox + w if direction == 1 else ox
            dir_label = "L>R" if direction == 1 else "R>L"
            lines.append(f"(ROW {row} — Y{fmt(y)} — {dir_label})")
            lines.append(f"G0 X{fmt(x_start)} Y{fmt(y)} (RAPID TO ROW START)")
            lines.append(f"G1 X{fmt(x_end)} F{f_val:.3f} (CUT ROW)")
            y += so
            direction *= -1

        lines.append(f"G0 Z{fmt(safe_z)} (RETRACT AFTER Z LEVEL)")


def _append_face_mill(
    lines: list, op: dict, feedrate, depth, safe_z: float | None
) -> None:
    """Legacy face_mill/face operation (uses old x_start/y_start/x_end/y_end params)."""
    params = op.get("parameters", {})
    x_start = float(params.get("x_start", 0.0))
    y_start = float(params.get("y_start", 0.0))
    x_end = float(params.get("x_end", 100.0))
    y_end = float(params.get("y_end", 100.0))
    stepover = float(op.get("stepover_mm", 10.0))
    z_cut = -abs(float(depth)) if depth else -1.0
    f = float(feedrate) if feedrate else 500.0

    lines.append(f"G0 X{fmt(x_start)} Y{fmt(y_start)} (RAPID TO START)")
    lines.append(f"G1 Z{fmt(z_cut)} F{f:.0f} (PLUNGE)")
    y = y_start
    direction = 1
    while y <= y_end + stepover:
        x_to = x_end if direction > 0 else x_start
        lines.append(f"G1 X{fmt(x_to)} Y{fmt(y)} F{f:.0f}")
        y += stepover
        direction *= -1
    if safe_z is not None:
        lines.append(f"G0 Z{fmt(safe_z)}")


def _append_laser(lines: list, op: dict, feedrate, params: dict) -> None:
    power = params.get("power_percent", 80)
    s_val = int(float(power) * 10)  # scale 0-100% to S0-1000
    f = float(feedrate) if feedrate else 1000.0
    x_start = float(params.get("x_start", 0.0))
    y_start = float(params.get("y_start", 0.0))
    x_end = float(params.get("x_end", 100.0))
    y_end = float(params.get("y_end", 0.0))

    lines.append(f"G0 X{fmt(x_start)} Y{fmt(y_start)}")
    lines.append(f"S{s_val} M3 (LASER ON)")
    lines.append(f"G1 X{fmt(x_end)} Y{fmt(y_end)} F{f:.0f}")
    lines.append("M5 S0 (LASER OFF)")
