"""GRBL postprocessor — GRBL 1.1 compatible G-code output.

Key GRBL differences from Fanuc:
- No % tape delimiters
- No O-number program identifier
- No M06 tool change (manual tool change only)
- Comments in () or ; style (both accepted)
- G28 goes to machine home (not relative Z move)
- No G49 tool length offset cancel (not supported)
- Laser mode: M3/M4 (S0-S1000 or S0-S255 depending on config)
- Feed hold and resume via real-time commands (not G-code)
- Supported canned cycles: G81, G82, G83 (in some GRBL builds — check firmware)
"""

from __future__ import annotations


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to GRBL 1.1 compatible G-code.

    Conservative output: operations that cannot be fully interpreted produce
    commented placeholders rather than unsafe moves.
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "mill")
    safe_z = float(operation_plan.get("safe_z", 10.0))
    wcs = operation_plan.get("work_coordinate_system", "G54")
    assumptions = operation_plan.get("assumptions", [])
    warnings = operation_plan.get("warnings", [])

    # --- Header (GRBL uses ; or () comments — using () for compatibility) ---
    lines.append(f"(GENERATED BY GENAI4G CNC - POSTPROCESSOR: GRBL)")
    lines.append(f"(MACHINE TYPE: {machine_type.upper()})")
    lines.append(f"(UNITS: {units.upper()})")
    lines.append(f"(SAFE Z: {safe_z})")
    lines.append(f"(WCS: {wcs})")
    for a in assumptions:
        lines.append(f"(ASSUMPTION: {a})")
    for w in warnings:
        lines.append(f"(WARNING: {w})")

    # --- Safety setup ---
    unit_code = "G21" if units == "mm" else "G20"
    lines.append(f"{unit_code}")
    lines.append("G90")           # absolute positioning
    lines.append("G94")           # feed per minute
    lines.append(f"{wcs}")        # work coordinate system

    # --- Operations ---
    operations = operation_plan.get("operations", [])
    # Build tool lookup supporting both tool_number and id
    tools: dict = {}
    for t in operation_plan.get("tools", []):
        if not isinstance(t, dict):
            continue
        if t.get("tool_number") is not None:
            tools[t["tool_number"]] = t
        if t.get("id") is not None:
            tools[t["id"]] = t

    if not operations:
        lines.append("(NO OPERATIONS DEFINED - SAFE SKELETON ONLY)")
    else:
        current_tool: object = None
        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"(SKIPPED: {op!r})")
                continue

            op_name = op.get("name") or op.get("description") or "UNNAMED"
            op_type = op.get("type", "unknown")
            tool_ref = op.get("tool_number") or op.get("tool_id")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            spindle = op.get("spindle_rpm") or op.get("spindle_speed")
            depth = op.get("depth_mm")
            params = op.get("parameters", {})

            lines.append(f"")
            lines.append(f"({op_name.upper()} - {op_type.upper()})")

            # GRBL: no automatic tool change — remind operator
            if tool_ref is not None and tool_ref != current_tool:
                tool_info = tools.get(tool_ref, {})
                desc = tool_info.get("description") or tool_info.get("name") or ""
                lines.append(f"(MANUAL TOOL CHANGE: T{tool_ref} - {desc})")
                lines.append(f"(PAUSE HERE TO CHANGE TOOL - RESUME WHEN READY)")
                current_tool = tool_ref

            # Retract to safe Z
            lines.append(f"G00 Z{safe_z:.3f}")

            # Spindle / laser
            spindle_started = False
            if spindle:
                lines.append(f"S{int(spindle)} M3")
                spindle_started = True
            else:
                lines.append("(WARNING: NO SPINDLE SPEED - M3 SKIPPED)")

            # Operation body
            if op_type in ("face_mill", "face"):
                _append_face_mill(lines, op, feedrate, depth, safe_z)
            elif op_type in ("pocket", "pocket_mill"):
                _append_pocket(lines, op, feedrate, depth)
            elif op_type in ("profile", "contour"):
                _append_profile(lines, op, feedrate, depth)
            elif op_type in ("drill", "drilling"):
                _append_drill(lines, op, feedrate, depth, safe_z)
            elif op_type in ("laser_cut", "laser_engrave", "laser_mark"):
                _append_laser(lines, op, feedrate, params)
            else:
                lines.append(f"(TODO: OP TYPE '{op_type}' NOT IMPLEMENTED)")
                lines.append(f"(PARAMS: {params})")

            lines.append(f"G00 Z{safe_z:.3f}")
            if spindle_started:
                lines.append("M5")    # spindle/laser off
            lines.append("M9")    # coolant off (if connected)

    # --- Program end ---
    lines.append("")
    lines.append(f"G00 Z{safe_z:.3f}")
    lines.append("M5")
    lines.append("M30")

    return "\n".join(lines)


def _append_face_mill(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    x_start = float(params.get("x_start", 0.0))
    y_start = float(params.get("y_start", 0.0))
    x_end = float(params.get("x_end", 100.0))
    y_end = float(params.get("y_end", 100.0))
    stepover = float(op.get("stepover_mm", 10.0))
    z_cut = -abs(depth) if depth else -1.0
    f = feedrate or 500

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f}")
    lines.append(f"G01 Z{z_cut:.3f} F{f:.0f}")
    y = y_start
    direction = 1
    while y <= y_end + stepover:
        x_to = x_end if direction > 0 else x_start
        lines.append(f"G01 X{x_to:.3f} Y{y:.3f} F{f:.0f}")
        y += stepover
        direction *= -1
    lines.append(f"G00 Z{safe_z:.3f}")


def _append_pocket(lines: list, op: dict, feedrate, depth) -> None:
    params = op.get("parameters", {})
    lines.append("(POCKET: PARAMETERS BELOW - FULL TOOLPATH REQUIRES CAM)")
    lines.append(f"(PARAMS: {params})")
    f = feedrate or 400
    z_cut = -abs(depth) if depth else -5.0
    lines.append(f"(PLUNGE DEPTH: Z{z_cut:.3f} F{f:.0f})")


def _append_profile(lines: list, op: dict, feedrate, depth) -> None:
    params = op.get("parameters", {})
    lines.append("(PROFILE: PARAMETERS BELOW - FULL TOOLPATH REQUIRES CAM)")
    lines.append(f"(PARAMS: {params})")


def _append_drill(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    """Generate GRBL drill moves. Handles both single-hole and multi-hole formats."""
    params = op.get("parameters", {})
    f = feedrate

    # --- New format: single hole with x, y, z in parameters ---
    x = params.get("x")
    y = params.get("y")
    z = params.get("z")

    if x is not None and y is not None and z is not None:
        if f is None:
            lines.append(f"(SKIPPED DRILL AT X{x} Y{y} Z{z} - NO FEEDRATE)")
            return
        z_float = float(z) if float(z) < 0 else -abs(float(z))
        lines.append(f"G00 X{float(x):.3f} Y{float(y):.3f}")
        lines.append(f"G01 Z{z_float:.3f} F{float(f):.3f}")
        lines.append(f"G00 Z{safe_z:.3f}")
        return

    # --- Old format: holes list ---
    holes = params.get("holes", [])
    f_val = f or 200
    z_cut = -abs(depth) if depth else -10.0
    r_plane = float(op.get("retract_height_mm", 2.0))

    if holes:
        for h in holes:
            hx, hy = float(h.get("x", 0.0)), float(h.get("y", 0.0))
            lines.append(f"G00 X{hx:.3f} Y{hy:.3f}")
            lines.append(f"G01 Z{z_cut:.3f} F{float(f_val):.3f}")
            lines.append(f"G00 Z{safe_z:.3f}")
    else:
        lines.append("(DRILL: NO HOLE COORDINATES PROVIDED - SKIPPING)")
        lines.append(f"(WOULD DRILL TO Z{z_cut:.3f} F{f_val:.0f})")


def _append_laser(lines: list, op: dict, feedrate, params: dict) -> None:
    power = params.get("power_percent", 80)
    # GRBL laser: S value 0-1000 (scaled from %)
    s_val = int(power * 10)
    f = feedrate or 1000
    x_end = float(params.get("x_end", 100.0))
    y_end = float(params.get("y_end", 0.0))
    x_start = float(params.get("x_start", 0.0))
    y_start = float(params.get("y_start", 0.0))

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f}")
    lines.append(f"S{s_val} M3")   # laser on at power
    lines.append(f"G01 X{x_end:.3f} Y{y_end:.3f} F{f:.0f}")
    lines.append("M5 S0")          # laser off
