"""LinuxCNC postprocessor — RS274NGC dialect (LinuxCNC / EMC2).

LinuxCNC differences from Fanuc:
- RS274NGC G-code dialect
- % tape delimiters (same as Fanuc)
- o-word subroutines: o100 sub / o100 endsub / o100 call
- Named parameters: #<param_name> = value
- M2 or M30 for program end
- G10 L2 for work offset setting
- Tool table via T<n> M06, then G43 H<n> for length compensation
- G41.1/G42.1 for cutter comp with diameter value
- Canned cycles: G81, G83, G76 (threading), G85
- No G80 needed after some cycles (LinuxCNC cancels automatically)
- Feed override and spindle override available
"""

from __future__ import annotations


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to LinuxCNC RS274NGC G-code.

    Conservative output: unrecognised operations produce commented
    placeholders rather than unsafe moves.
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "mill")
    safe_z = float(operation_plan.get("safe_z", 10.0))
    wcs = operation_plan.get("work_coordinate_system", "G54")
    assumptions = operation_plan.get("assumptions", [])
    warnings = operation_plan.get("warnings", [])

    # --- Header ---
    lines.append("%")
    lines.append(f"(GENERATED BY GENAI4G CNC - POSTPROCESSOR: LINUXCNC)")
    lines.append(f"(MACHINE TYPE: {machine_type.upper()})")
    lines.append(f"(UNITS: {units.upper()})")
    lines.append(f"(SAFE Z: {safe_z})")
    lines.append(f"(WCS: {wcs})")
    for a in assumptions:
        lines.append(f"(ASSUMPTION: {a})")
    for w in warnings:
        lines.append(f"(WARNING: {w})")

    # --- Safety setup ---
    lines.append("G17 G40 G49 G80    (SAFETY: XY-plane, cancel comp, TLO, cycles)")
    unit_code = "G21" if units == "mm" else "G20"
    lines.append(f"{unit_code}                 (UNITS: {'MM' if units == 'mm' else 'INCH'})")
    lines.append("G90                (ABSOLUTE POSITIONING)")
    lines.append("G94                (FEED PER MINUTE)")
    lines.append(f"{wcs}               (WORK COORDINATE SYSTEM)")

    # --- Operations ---
    operations = operation_plan.get("operations", [])
    tools = {
        t.get("tool_number"): t
        for t in operation_plan.get("tools", [])
        if isinstance(t, dict)
    }

    if not operations:
        lines.append("(NO OPERATIONS DEFINED - SAFE SKELETON ONLY)")
    else:
        current_tool: object = None
        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"(SKIPPED: {op!r})")
                continue

            op_name = op.get("name", "UNNAMED")
            op_type = op.get("type", "unknown")
            tool_num = op.get("tool_number")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            spindle = op.get("spindle_rpm")
            depth = op.get("depth_mm")
            params = op.get("parameters", {})

            lines.append("")
            lines.append(f"({op_name.upper()} - TYPE: {op_type.upper()})")

            # Tool change — LinuxCNC uses T<n> M06 then G43 H<n>
            if tool_num is not None and tool_num != current_tool:
                tool_info = tools.get(tool_num, {})
                desc = tool_info.get("description", "")
                lines.append(f"(TOOL {tool_num}: {desc})")
                lines.append(f"T{tool_num} M06          (TOOL CHANGE)")
                lines.append(f"G43 H{tool_num}           (TOOL LENGTH COMPENSATION)")
                current_tool = tool_num

            lines.append(f"G00 Z{safe_z:.3f}        (RETRACT TO SAFE Z)")

            if spindle:
                lines.append(f"S{int(spindle)} M03         (SPINDLE CW)")
            else:
                lines.append("(WARNING: NO SPINDLE SPEED)")

            if op_type in ("face_mill", "face"):
                _append_face_mill(lines, op, feedrate, depth, safe_z)
            elif op_type in ("pocket", "pocket_mill"):
                _append_pocket(lines, op, feedrate, depth)
            elif op_type in ("profile", "contour"):
                _append_profile(lines, op, feedrate, depth)
            elif op_type in ("drill", "drilling"):
                _append_drill(lines, op, feedrate, depth, safe_z)
            elif op_type in ("bore",):
                _append_bore(lines, op, feedrate, depth, safe_z)
            else:
                lines.append(f"(TODO: OP TYPE '{op_type}' NOT IMPLEMENTED)")
                lines.append(f"(PARAMS: {params})")

            lines.append(f"G00 Z{safe_z:.3f}        (RETRACT)")
            lines.append("M05                (SPINDLE STOP)")
            lines.append("M09                (COOLANT OFF)")

    # --- Program end ---
    lines.append("")
    lines.append("G49                (CANCEL TOOL LENGTH COMP)")
    lines.append("G28 G91 Z0.        (RETURN Z TO HOME)")
    lines.append("G90")
    lines.append("M02                (PROGRAM END)")
    lines.append("%")

    return "\n".join(lines)


def _append_face_mill(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    x_start = float(params.get("x_start", 0.0))
    y_start = float(params.get("y_start", 0.0))
    x_end = float(params.get("x_end", 100.0))
    y_end = float(params.get("y_end", 100.0))
    stepover = float(op.get("stepover_mm", 10.0))
    z_cut = -abs(depth) if depth else -1.0
    f = feedrate or 500

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f}")
    lines.append(f"G01 Z{z_cut:.3f} F{f:.0f}")
    y = y_start
    direction = 1
    while y <= y_end + stepover:
        x_to = x_end if direction > 0 else x_start
        lines.append(f"G01 X{x_to:.3f} Y{y:.3f} F{f:.0f}")
        y += stepover
        direction *= -1
    lines.append(f"G00 Z{safe_z:.3f}")


def _append_pocket(lines: list, op: dict, feedrate, depth) -> None:
    params = op.get("parameters", {})
    lines.append("(POCKET: FULL TOOLPATH REQUIRES CAM)")
    lines.append(f"(PARAMS: {params})")
    f = feedrate or 400
    z_cut = -abs(depth) if depth else -5.0
    lines.append(f"(PLUNGE DEPTH: Z{z_cut:.3f} F{f:.0f})")


def _append_profile(lines: list, op: dict, feedrate, depth) -> None:
    params = op.get("parameters", {})
    lines.append("(PROFILE: FULL TOOLPATH REQUIRES CAM)")
    lines.append(f"(PARAMS: {params})")


def _append_drill(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    holes = params.get("holes", [])
    f = feedrate or 200
    z_cut = -abs(depth) if depth else -10.0
    r_plane = float(op.get("retract_height_mm", 2.0))
    peck = max(1.0, abs(z_cut) / 5.0)

    if holes:
        for h in holes:
            x, y = float(h.get("x", 0.0)), float(h.get("y", 0.0))
            lines.append(
                f"G83 X{x:.3f} Y{y:.3f} Z{z_cut:.3f} "
                f"R{r_plane:.3f} Q{peck:.3f} F{f:.0f}"
            )
        lines.append("G80                (CANCEL CANNED CYCLE)")
    else:
        lines.append("(DRILL: NO HOLE COORDS)")
        lines.append(f"(WOULD DRILL TO Z{z_cut:.3f} F{f:.0f})")


def _append_bore(lines: list, op: dict, feedrate, depth, safe_z: float) -> None:
    params = op.get("parameters", {})
    x = float(params.get("x", 0.0))
    y = float(params.get("y", 0.0))
    f = feedrate or 100
    z_cut = -abs(depth) if depth else -10.0
    r_plane = float(op.get("retract_height_mm", 2.0))

    # G85: bore in, feed out (no spindle stop)
    lines.append(
        f"G85 X{x:.3f} Y{y:.3f} Z{z_cut:.3f} R{r_plane:.3f} F{f:.0f}  (BORE)"
    )
    lines.append("G80                (CANCEL CANNED CYCLE)")
