"""Marlin postprocessor — Marlin firmware G-code (laser engravers and 3D printers).

Marlin differences from Fanuc:
- M104/M109 hotend temperature (3D print)
- M140/M190 bed temperature (3D print)
- M106/M107 fan control
- G28 homes all axes
- Laser power: M3/M4 S<0-255> (inline or dynamic power mode)
- No O-number, no % delimiters (optional %)
- M0/M1 for unconditional pause (tool change prompt)
- Extrusion via E axis (3D print only)
"""

from __future__ import annotations


def generate_gcode_from_operations(operation_plan: dict) -> str:
    """Convert a structured operation plan to Marlin-compatible G-code.

    Handles two main Marlin use cases:
    - Laser engraving/cutting (machine_type: laser)
    - 3D printing skeleton (machine_type: 3d_printer) — full toolpath requires slicer
    """
    lines: list[str] = []
    units = operation_plan.get("units", "mm")
    machine_type = operation_plan.get("machine_type", "laser")
    safe_z = float(operation_plan.get("safe_z", 5.0))
    assumptions = operation_plan.get("assumptions", [])
    warnings = operation_plan.get("warnings", [])

    # --- Header ---
    lines.append(f"; Generated by GenAI4G CNC - Marlin postprocessor")
    lines.append(f"; Machine: {machine_type.upper()}")
    lines.append(f"; Units: {units.upper()}")
    for a in assumptions:
        lines.append(f"; Assumption: {a}")
    for w in warnings:
        lines.append(f"; WARNING: {w}")

    # --- Safety: laser/spindle off at start ---
    lines.append("M5 S0            ; Laser/spindle OFF (safety)")
    unit_code = "G21" if units == "mm" else "G20"
    lines.append(f"{unit_code}               ; Units")
    lines.append("G90              ; Absolute positioning")
    lines.append("G94              ; Feed per minute")

    if machine_type == "3d_printer":
        _write_3d_printer_header(lines, operation_plan)
    else:
        _write_laser_header(lines, safe_z)

    # --- Operations ---
    operations = operation_plan.get("operations", [])

    if not operations:
        lines.append("; NO OPERATIONS DEFINED - SKELETON ONLY")
    else:
        for op in operations:
            if not isinstance(op, dict):
                lines.append(f"; SKIPPED: {op!r}")
                continue

            op_name = op.get("name", "UNNAMED")
            op_type = op.get("type", "unknown")
            feedrate = op.get("feedrate_mmpm") or op.get("feedrate")
            params = op.get("parameters", {})

            lines.append(f"")
            lines.append(f"; --- {op_name.upper()} ({op_type.upper()}) ---")

            if op_type in ("laser_cut", "laser_engrave", "laser_mark"):
                _append_laser_op(lines, op, feedrate, params, safe_z)
            elif machine_type == "3d_printer":
                _append_print_op(lines, op, feedrate, params)
            else:
                lines.append(f"; TODO: op type '{op_type}' not implemented")
                lines.append(f"; Params: {params}")

    # --- End ---
    lines.append("")
    lines.append(f"G00 Z{safe_z:.3f}    ; Retract to safe Z")
    lines.append("M5 S0            ; Laser/spindle OFF")

    if machine_type == "3d_printer":
        lines.append("M104 S0          ; Hotend off")
        lines.append("M140 S0          ; Bed off")
        lines.append("M107             ; Fan off")
        lines.append("G28 X Y          ; Park head")
    else:
        lines.append("G28 X Y          ; Park at home")

    lines.append("M30              ; Program end")

    return "\n".join(lines)


def _write_3d_printer_header(lines: list, plan: dict) -> None:
    hotend_temp = plan.get("hotend_temp_c", 200)
    bed_temp = plan.get("bed_temp_c", 60)
    lines.append(f"M140 S{bed_temp}         ; Set bed temp (no wait)")
    lines.append(f"M104 S{hotend_temp}       ; Set hotend temp (no wait)")
    lines.append("G28              ; Home all axes")
    lines.append("G29              ; Auto bed levelling (remove if not fitted)")
    lines.append(f"M190 S{bed_temp}         ; Wait for bed temp")
    lines.append(f"M109 S{hotend_temp}       ; Wait for hotend temp")
    lines.append("M106 S255        ; Fan on full")
    lines.append("G92 E0           ; Reset extruder")


def _write_laser_header(lines: list, safe_z: float) -> None:
    lines.append("G28              ; Home all axes")
    lines.append(f"G00 Z{safe_z:.3f}    ; Move to safe Z (focus height)")
    lines.append("; NOTE: Set laser focus height manually before running")


def _append_laser_op(lines: list, op: dict, feedrate, params: dict, safe_z: float) -> None:
    power_pct = float(params.get("power_percent", 80))
    s_val = int(power_pct * 2.55)   # scale 0-100% to 0-255
    f = feedrate or 1000
    passes = int(params.get("passes", 1))
    x_start = float(params.get("x_start", 0.0))
    y_start = float(params.get("y_start", 0.0))
    x_end = float(params.get("x_end", 100.0))
    y_end = float(params.get("y_end", 0.0))

    lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f}  ; Rapid to start")
    for p in range(passes):
        if passes > 1:
            lines.append(f"; Pass {p + 1} of {passes}")
        lines.append(f"M3 S{s_val}          ; Laser ON ({power_pct:.0f}%)")
        lines.append(f"G01 X{x_end:.3f} Y{y_end:.3f} F{f:.0f}")
        lines.append("M5 S0            ; Laser OFF")
        if p < passes - 1:
            lines.append(f"G00 X{x_start:.3f} Y{y_start:.3f}")


def _append_print_op(lines: list, op: dict, feedrate, params: dict) -> None:
    lines.append(f"; 3D print op: {op.get('type')} — full toolpath requires slicer")
    lines.append(f"; Params: {params}")
    lines.append("; TODO: Import slicer-generated layer G-code here")
