"""Demo: Deterministic G-code regeneration from OperationPlan.

Shows that abbreviated/truncated agent G-code is discarded and replaced
with deterministic output generated by the postprocessor pipeline.

Run without API key:
    python scripts/demo_deterministic_regeneration.py
"""

from __future__ import annotations

from cnc.tools.gcode_pipeline import regenerate_gcode_from_operation_plan


# ---------------------------------------------------------------------------
# Fake agent result — simulates what an LLM agent might return after
# abbreviating a long G-code block in its JSON response.
# ---------------------------------------------------------------------------

VALID_DRILL_PLAN = {
    "machine_type": "drill",
    "units": "mm",
    "work_coordinate_system": "G54",
    "safe_z": 5,
    "tools": [
        {
            "id": "T1",
            "name": "5mm drill",
            "diameter": 5,
            "units": "mm",
            "spindle_speed": 1200,
            "feedrate": 100,
        }
    ],
    "operations": [
        {
            "type": "drill",
            "description": "Drill one hole at X0 Y0 to Z-5",
            "tool_id": "T1",
            "parameters": {"x": 0, "y": 0, "z": -5},
            "feedrate": 100,
            "spindle_speed": 1200,
        }
    ],
    "assumptions": [],
    "warnings": [],
}

ABBREVIATED_AGENT_GCODE = (
    "G21\nG90\nG54\n"
    "S1200 M03\n"
    "G00 X0 Y0\n"
    "... [18 rows x 4 passes]\n"
    "M05\nM30"
)

FAKE_AGENT_RESULT = {
    "ok": True,
    "machine_type": "drill",
    "operation_plan": VALID_DRILL_PLAN,
    "gcode": ABBREVIATED_AGENT_GCODE,
    "warnings": [],
    "errors": [],
}


def main() -> None:
    print("=" * 60)
    print("DEMO: Deterministic G-code Regeneration")
    print("=" * 60)

    print("\n[1] Fake agent result — abbreviated G-code:")
    preview = ABBREVIATED_AGENT_GCODE[:120].replace("\n", "\\n")
    print(f"    gcode preview: {preview!r}")

    # Run the pipeline
    result = regenerate_gcode_from_operation_plan(FAKE_AGENT_RESULT)

    print("\n[2] Regenerated G-code (deterministic):")
    for line in result["gcode"].splitlines():
        print(f"    {line}")

    print(f"\n[3] ok: {result.get('ok')}")
    print(f"    postprocessor: {result.get('postprocessor')}")

    print("\n[4] Warnings:")
    for w in result.get("warnings", []):
        print(f"    - {w}")

    print("\n[5] Errors:")
    errors = result.get("errors", [])
    if errors:
        for e in errors:
            print(f"    ! {e}")
    else:
        print("    (none)")

    val = result.get("validation", {})
    print(f"\n[6] Validation ok: {val.get('ok')}")
    for e in val.get("errors", []):
        print(f"    error: {e}")
    for w in val.get("warnings", []):
        print(f"    warning: {w}")

    # Verify abbreviated placeholder is gone
    assert "[18 rows" not in result["gcode"], \
        "BUG: abbreviated placeholder found in deterministic output!"
    assert result["gcode"].strip(), "BUG: G-code is empty!"
    print("\n[OK] Abbreviated placeholder not present in final output.")
    print("[OK] Demo completed successfully — no API key required.")


if __name__ == "__main__":
    main()
